# name: Breaking Math CI
# on: pull_request

# jobs:
#   build:
#     name: Install, build, and test Breaking Math
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1
#       - uses: dcodeIO/setup-node-nvm@master
#         with:
#           node-version: lts/*
#       - name: npm install, build, and test
#         run: |
#           npm ci &&
#           npm run build --if-present
#           npm test
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#           CI: true
# env:
#   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
