on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: breaking-math
          SLACK_COLOR: "#32B853"
          SLACK_ICON: https://scontent-lga3-1.xx.fbcdn.net/v/t31.0-8/16797445_1422127367858348_1435345743718530782_o.jpg?_nc_cat=111&_nc_oc=AQm8l8JyjUYgn52-JRODsB5Bv7X_bkmmLSQPqXFAdbJ7-CPiEL8LWWB0v15PoGz6-Zc&_nc_ht=scontent-lga3-1.xx&oh=19cec50f95244901a6846bdd62cc1516&oe=5E2A18AD
          SLACK_MESSAGE: "@here New PR ready for review :rocket:"
          SLACK_TITLE: Message
          SLACK_USERNAME: MathBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
