name: Deploy-Prod
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: NVM Node LTS version
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: run build
        run: |
          npm ci && 
          npm run build --if-present

      - name: Deploy to Firebase Production
        if: success()

        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
