name: Breaking Math CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v1

      - name: NVM Node LTS version
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: run tests
        run: |
          npm ci &&
          npm run test
